/********************************************************************************
** Form generated from reading ui file 'parameterform.ui'
**
** Created: Wed Jan 8 15:11:24 2020
**      by: Qt User Interface Compiler version 4.5.2
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

#ifndef UI_PARAMETERFORM_H
#define UI_PARAMETERFORM_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include "slgfwcheckbox.h"
#include "slgfwdialogform.h"
#include "slgfwgroupbox.h"
#include "slgfwlabel.h"
#include "slgfwlineedit.h"

QT_BEGIN_NAMESPACE

class Ui_ParameterFormUi
{
public:
    SlGfwLabel *label_36;
    SlGfwLabel *label_32;
    SlGfwLabel *label_24;
    SlGfwLabel *label_30;
    SlGfwLabel *label;
    SlGfwGroupBox *groupBox;
    SlGfwLabel *label_2;
    SlGfwLabel *label_6;
    SlGfwLabel *label_7;
    SlGfwLineEdit *LH_CuttingDepthLineEdit;
    SlGfwLineEdit *LV_CuttingDepthLineEdit;
    SlGfwLabel *label_8;
    SlGfwLabel *label_9;
    SlGfwLabel *label_14;
    SlGfwLineEdit *LV_PowerControlLineEdit;
    SlGfwLabel *label_15;
    SlGfwLineEdit *H_DeviceIniPosLineEdit;
    SlGfwLabel *label_34;
    SlGfwLabel *label_35;
    SlGfwLineEdit *V_WorkIniPosLineEdit;
    SlGfwLabel *label_33;
    SlGfwLabel *label_29;
    SlGfwLabel *label_31;
    SlGfwGroupBox *groupBox_2;
    SlGfwLabel *label_3;
    SlGfwLabel *label_10;
    SlGfwLineEdit *RH_CuttingDepthLineEdit;
    SlGfwLabel *label_11;
    SlGfwLineEdit *RV_CuttingDepthLineEdit;
    SlGfwLabel *label_12;
    SlGfwLabel *label_13;
    SlGfwLabel *label_16;
    SlGfwLabel *label_17;
    SlGfwLineEdit *RV_PowerControlLineEdit;
    SlGfwGroupBox *groupBox_5;
    SlGfwLabel *label_37;
    SlGfwLabel *label_38;
    SlGfwLineEdit *SlopeLengthLineEdit;
    SlGfwLabel *label_39;
    SlGfwLabel *label_40;
    SlGfwLineEdit *TrainSpeedLineEdit;
    SlGfwLabel *label_41;
    SlGfwLabel *label_42;
    SlGfwLineEdit *AxisLineSpeedLineEdit;
    SlGfwLabel *label_43;
    SlGfwLineEdit *MillingModuleLineEdit;
    SlGfwLabel *label_44;
    SlGfwLabel *label_45;
    SlGfwLineEdit *PowerControlSelectLineEdit;
    SlGfwCheckBox *PowerControlSelectCheckBox;
    SlGfwGroupBox *groupBox_6;
    SlGfwLabel *label_46;
    SlGfwLabel *label_48;
    SlGfwLineEdit *SlopeLengthLineEdit_2;
    SlGfwLabel *label_49;
    SlGfwLabel *label_50;
    SlGfwLineEdit *TrainSpeedLineEdit_2;
    SlGfwLabel *label_51;
    SlGfwLabel *label_52;
    SlGfwLineEdit *AxisLineSpeedLineEdit_2;
    SlGfwLabel *label_53;
    SlGfwLineEdit *MillingModuleLineEdit_2;
    SlGfwLabel *label_54;
    SlGfwLabel *label_55;
    SlGfwLineEdit *PowerControlSelectLineEdit_2;
    SlGfwCheckBox *PowerControlSelectCheckBox_2;
    SlGfwLabel *label_56;
    SlGfwLineEdit *TrainSpdDiffLineEdit_2;
    SlGfwGroupBox *groupBox_7;
    SlGfwLabel *label_22;
    SlGfwLineEdit *TrainSpdDiffLineEdit;
    SlGfwLabel *label_26;
    SlGfwLabel *label_57;
    SlGfwLineEdit *TrainSpdDiffTimeLineEdit;
    SlGfwLabel *label_27;
    SlGfwLabel *label_28;
    SlGfwLabel *label_47;
    SlGfwLineEdit *H_WorkIniPosLineEdit;
    SlGfwLineEdit *V_DeviceIniPosLineEdit;

    void setupUi(SlGfwDialogForm *ParameterFormUi)
    {
        if (ParameterFormUi->objectName().isEmpty())
            ParameterFormUi->setObjectName(QString::fromUtf8("ParameterFormUi"));
        ParameterFormUi->resize(600, 373);
        QPalette palette;
        QBrush brush(QColor(60, 100, 220, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        QBrush brush1(QColor(135, 165, 205, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush1);
        QBrush brush2(QColor(241, 239, 226, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush2);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush1);
        QBrush brush3(QColor(149, 149, 151, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush3);
        QBrush brush4(QColor(0, 0, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Text, brush4);
        QBrush brush5(QColor(255, 255, 255, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush5);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush5);
        QBrush brush6(QColor(215, 225, 235, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush6);
        QBrush brush7(QColor(113, 111, 100, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush7);
        QBrush brush8(QColor(178, 180, 191, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Highlight, brush8);
        palette.setBrush(QPalette::Active, QPalette::HighlightedText, brush4);
        QBrush brush9(QColor(0, 0, 255, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Link, brush9);
        QBrush brush10(QColor(255, 0, 255, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::LinkVisited, brush10);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush7);
        QBrush brush11(QColor(224, 223, 227, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Inactive, QPalette::Highlight, brush11);
        palette.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Link, brush9);
        palette.setBrush(QPalette::Inactive, QPalette::LinkVisited, brush10);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        QBrush brush12(QColor(239, 239, 241, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush12);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        QBrush brush13(QColor(75, 95, 135, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush13);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Highlight, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Link, brush9);
        palette.setBrush(QPalette::Disabled, QPalette::LinkVisited, brush10);
        ParameterFormUi->setPalette(palette);
        ParameterFormUi->setFocusPolicy(Qt::NoFocus);
        ParameterFormUi->setBaseSize(QSize(640, 480));
        ParameterFormUi->setPositionsScaleMode(SlGfwDialogForm::SL_GFW_PERCENT);
        label_36 = new SlGfwLabel(ParameterFormUi);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(240, 340, 31, 31));
        label_32 = new SlGfwLabel(ParameterFormUi);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(520, 310, 31, 31));
        label_24 = new SlGfwLabel(ParameterFormUi);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(13, 290, 100, 21));
        label_24->setAutoFillBackground(false);
        label_24->setInverseColors(true);
        label_30 = new SlGfwLabel(ParameterFormUi);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(240, 310, 31, 31));
        label = new SlGfwLabel(ParameterFormUi);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(210, 26, 171, 31));
        QFont font;
        font.setFamily(QString::fromUtf8("Siemens AD CH Simplified"));
        font.setBold(false);
        font.setWeight(50);
        label->setFont(font);
        label->setAutoFillBackground(false);
        label->setAlignment(Qt::AlignCenter);
        groupBox = new SlGfwGroupBox(ParameterFormUi);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(-6, 60, 301, 231));
        groupBox->setAutoFillBackground(false);
        groupBox->setHmiFonts(true);
        groupBox->setHmiColors(true);
        groupBox->setNavigationMode(true);
        groupBox->setHmiUseBigFont(false);
        groupBox->setHmiFontSize(12);
        groupBox->setFlat(false);
        groupBox->setCheckable(false);
        label_2 = new SlGfwLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 0, 100, 21));
        label_2->setFont(font);
        label_2->setAutoFillBackground(false);
        label_2->setHmiFonts(true);
        label_2->setHmiColors(true);
        label_2->setInverseColors(true);
        label_6 = new SlGfwLabel(groupBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(22, 50, 81, 31));
        label_7 = new SlGfwLabel(groupBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(160, 50, 31, 31));
        LH_CuttingDepthLineEdit = new SlGfwLineEdit(groupBox);
        LH_CuttingDepthLineEdit->setObjectName(QString::fromUtf8("LH_CuttingDepthLineEdit"));
        LH_CuttingDepthLineEdit->setGeometry(QRect(102, 51, 51, 27));
        LH_CuttingDepthLineEdit->setAlignment(Qt::AlignHCenter);
        LV_CuttingDepthLineEdit = new SlGfwLineEdit(groupBox);
        LV_CuttingDepthLineEdit->setObjectName(QString::fromUtf8("LV_CuttingDepthLineEdit"));
        LV_CuttingDepthLineEdit->setGeometry(QRect(102, 102, 51, 27));
        LV_CuttingDepthLineEdit->setAlignment(Qt::AlignHCenter);
        label_8 = new SlGfwLabel(groupBox);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(22, 100, 81, 31));
        label_9 = new SlGfwLabel(groupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(160, 100, 31, 31));
        label_14 = new SlGfwLabel(groupBox);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(22, 150, 81, 31));
        LV_PowerControlLineEdit = new SlGfwLineEdit(groupBox);
        LV_PowerControlLineEdit->setObjectName(QString::fromUtf8("LV_PowerControlLineEdit"));
        LV_PowerControlLineEdit->setGeometry(QRect(102, 152, 51, 27));
        LV_PowerControlLineEdit->setAlignment(Qt::AlignHCenter);
        label_15 = new SlGfwLabel(groupBox);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(160, 150, 31, 31));
        H_DeviceIniPosLineEdit = new SlGfwLineEdit(ParameterFormUi);
        H_DeviceIniPosLineEdit->setObjectName(QString::fromUtf8("H_DeviceIniPosLineEdit"));
        H_DeviceIniPosLineEdit->setGeometry(QRect(182, 310, 51, 27));
        H_DeviceIniPosLineEdit->setAlignment(Qt::AlignHCenter);
        label_34 = new SlGfwLabel(ParameterFormUi);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(520, 340, 31, 31));
        label_35 = new SlGfwLabel(ParameterFormUi);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(55, 340, 121, 31));
        V_WorkIniPosLineEdit = new SlGfwLineEdit(ParameterFormUi);
        V_WorkIniPosLineEdit->setObjectName(QString::fromUtf8("V_WorkIniPosLineEdit"));
        V_WorkIniPosLineEdit->setGeometry(QRect(462, 340, 51, 27));
        V_WorkIniPosLineEdit->setAlignment(Qt::AlignHCenter);
        label_33 = new SlGfwLabel(ParameterFormUi);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(345, 340, 121, 31));
        label_29 = new SlGfwLabel(ParameterFormUi);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(55, 310, 121, 31));
        label_31 = new SlGfwLabel(ParameterFormUi);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(345, 310, 121, 31));
        groupBox_2 = new SlGfwGroupBox(ParameterFormUi);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(293, 60, 301, 231));
        groupBox_2->setAutoFillBackground(false);
        groupBox_2->setHmiFontSize(12);
        groupBox_2->setCheckable(false);
        label_3 = new SlGfwLabel(groupBox_2);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(170, 0, 100, 21));
        label_3->setAutoFillBackground(false);
        label_3->setInverseColors(true);
        label_10 = new SlGfwLabel(groupBox_2);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(101, 50, 81, 31));
        RH_CuttingDepthLineEdit = new SlGfwLineEdit(groupBox_2);
        RH_CuttingDepthLineEdit->setObjectName(QString::fromUtf8("RH_CuttingDepthLineEdit"));
        RH_CuttingDepthLineEdit->setGeometry(QRect(183, 50, 51, 27));
        RH_CuttingDepthLineEdit->setAlignment(Qt::AlignHCenter);
        label_11 = new SlGfwLabel(groupBox_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(241, 49, 31, 31));
        RV_CuttingDepthLineEdit = new SlGfwLineEdit(groupBox_2);
        RV_CuttingDepthLineEdit->setObjectName(QString::fromUtf8("RV_CuttingDepthLineEdit"));
        RV_CuttingDepthLineEdit->setGeometry(QRect(183, 101, 51, 27));
        RV_CuttingDepthLineEdit->setAlignment(Qt::AlignHCenter);
        label_12 = new SlGfwLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(101, 98, 81, 31));
        label_13 = new SlGfwLabel(groupBox_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(241, 99, 31, 31));
        label_16 = new SlGfwLabel(groupBox_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(241, 148, 31, 31));
        label_17 = new SlGfwLabel(groupBox_2);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(101, 147, 81, 31));
        RV_PowerControlLineEdit = new SlGfwLineEdit(groupBox_2);
        RV_PowerControlLineEdit->setObjectName(QString::fromUtf8("RV_PowerControlLineEdit"));
        RV_PowerControlLineEdit->setGeometry(QRect(183, 150, 51, 27));
        RV_PowerControlLineEdit->setAlignment(Qt::AlignHCenter);
        groupBox_5 = new SlGfwGroupBox(ParameterFormUi);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(187, 60, 201, 231));
        groupBox_5->setMouseTracking(false);
        groupBox_5->setAutoFillBackground(true);
        label_37 = new SlGfwLabel(groupBox_5);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(6, 42, 81, 31));
        label_38 = new SlGfwLabel(groupBox_5);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(152, 10, 41, 31));
        SlopeLengthLineEdit = new SlGfwLineEdit(groupBox_5);
        SlopeLengthLineEdit->setObjectName(QString::fromUtf8("SlopeLengthLineEdit"));
        SlopeLengthLineEdit->setGeometry(QRect(96, 42, 51, 27));
        SlopeLengthLineEdit->setAlignment(Qt::AlignHCenter);
        label_39 = new SlGfwLabel(groupBox_5);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(6, 10, 81, 31));
        label_40 = new SlGfwLabel(groupBox_5);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(152, 42, 31, 31));
        TrainSpeedLineEdit = new SlGfwLineEdit(groupBox_5);
        TrainSpeedLineEdit->setObjectName(QString::fromUtf8("TrainSpeedLineEdit"));
        TrainSpeedLineEdit->setGeometry(QRect(96, 10, 51, 27));
        TrainSpeedLineEdit->setAlignment(Qt::AlignHCenter);
        label_41 = new SlGfwLabel(groupBox_5);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(6, 72, 81, 31));
        label_42 = new SlGfwLabel(groupBox_5);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(152, 72, 41, 31));
        AxisLineSpeedLineEdit = new SlGfwLineEdit(groupBox_5);
        AxisLineSpeedLineEdit->setObjectName(QString::fromUtf8("AxisLineSpeedLineEdit"));
        AxisLineSpeedLineEdit->setGeometry(QRect(96, 72, 51, 27));
        AxisLineSpeedLineEdit->setAlignment(Qt::AlignHCenter);
        AxisLineSpeedLineEdit->setReadOnly(true);
        label_43 = new SlGfwLabel(groupBox_5);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(6, 102, 91, 31));
        MillingModuleLineEdit = new SlGfwLineEdit(groupBox_5);
        MillingModuleLineEdit->setObjectName(QString::fromUtf8("MillingModuleLineEdit"));
        MillingModuleLineEdit->setGeometry(QRect(96, 102, 51, 27));
        MillingModuleLineEdit->setAlignment(Qt::AlignHCenter);
        MillingModuleLineEdit->setReadOnly(true);
        label_44 = new SlGfwLabel(groupBox_5);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(152, 100, 51, 31));
        label_45 = new SlGfwLabel(groupBox_5);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(6, 132, 91, 31));
        PowerControlSelectLineEdit = new SlGfwLineEdit(groupBox_5);
        PowerControlSelectLineEdit->setObjectName(QString::fromUtf8("PowerControlSelectLineEdit"));
        PowerControlSelectLineEdit->setGeometry(QRect(96, 132, 51, 27));
        PowerControlSelectLineEdit->setAlignment(Qt::AlignHCenter);
        PowerControlSelectLineEdit->setReadOnly(true);
        PowerControlSelectCheckBox = new SlGfwCheckBox(groupBox_5);
        PowerControlSelectCheckBox->setObjectName(QString::fromUtf8("PowerControlSelectCheckBox"));
        PowerControlSelectCheckBox->setEnabled(false);
        PowerControlSelectCheckBox->setGeometry(QRect(150, 130, 31, 31));
        groupBox_6 = new SlGfwGroupBox(groupBox_5);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(40, 230, 201, 231));
        groupBox_6->setMouseTracking(false);
        groupBox_6->setAutoFillBackground(true);
        label_46 = new SlGfwLabel(groupBox_6);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(6, 42, 81, 31));
        label_48 = new SlGfwLabel(groupBox_6);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(152, 10, 41, 31));
        SlopeLengthLineEdit_2 = new SlGfwLineEdit(groupBox_6);
        SlopeLengthLineEdit_2->setObjectName(QString::fromUtf8("SlopeLengthLineEdit_2"));
        SlopeLengthLineEdit_2->setGeometry(QRect(96, 42, 51, 27));
        SlopeLengthLineEdit_2->setAlignment(Qt::AlignHCenter);
        label_49 = new SlGfwLabel(groupBox_6);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(6, 10, 81, 31));
        label_50 = new SlGfwLabel(groupBox_6);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(152, 42, 31, 31));
        TrainSpeedLineEdit_2 = new SlGfwLineEdit(groupBox_6);
        TrainSpeedLineEdit_2->setObjectName(QString::fromUtf8("TrainSpeedLineEdit_2"));
        TrainSpeedLineEdit_2->setGeometry(QRect(96, 10, 51, 27));
        TrainSpeedLineEdit_2->setAlignment(Qt::AlignHCenter);
        label_51 = new SlGfwLabel(groupBox_6);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(6, 72, 81, 31));
        label_52 = new SlGfwLabel(groupBox_6);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(152, 72, 41, 31));
        AxisLineSpeedLineEdit_2 = new SlGfwLineEdit(groupBox_6);
        AxisLineSpeedLineEdit_2->setObjectName(QString::fromUtf8("AxisLineSpeedLineEdit_2"));
        AxisLineSpeedLineEdit_2->setGeometry(QRect(96, 72, 51, 27));
        AxisLineSpeedLineEdit_2->setAlignment(Qt::AlignHCenter);
        AxisLineSpeedLineEdit_2->setReadOnly(true);
        label_53 = new SlGfwLabel(groupBox_6);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(6, 102, 91, 31));
        MillingModuleLineEdit_2 = new SlGfwLineEdit(groupBox_6);
        MillingModuleLineEdit_2->setObjectName(QString::fromUtf8("MillingModuleLineEdit_2"));
        MillingModuleLineEdit_2->setGeometry(QRect(96, 102, 51, 27));
        MillingModuleLineEdit_2->setAlignment(Qt::AlignHCenter);
        MillingModuleLineEdit_2->setReadOnly(true);
        label_54 = new SlGfwLabel(groupBox_6);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(152, 100, 51, 31));
        label_55 = new SlGfwLabel(groupBox_6);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(6, 132, 91, 31));
        PowerControlSelectLineEdit_2 = new SlGfwLineEdit(groupBox_6);
        PowerControlSelectLineEdit_2->setObjectName(QString::fromUtf8("PowerControlSelectLineEdit_2"));
        PowerControlSelectLineEdit_2->setGeometry(QRect(96, 132, 51, 27));
        PowerControlSelectLineEdit_2->setAlignment(Qt::AlignHCenter);
        PowerControlSelectLineEdit_2->setReadOnly(true);
        PowerControlSelectCheckBox_2 = new SlGfwCheckBox(groupBox_6);
        PowerControlSelectCheckBox_2->setObjectName(QString::fromUtf8("PowerControlSelectCheckBox_2"));
        PowerControlSelectCheckBox_2->setEnabled(false);
        PowerControlSelectCheckBox_2->setGeometry(QRect(150, 130, 31, 31));
        label_56 = new SlGfwLabel(groupBox_6);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(90, 200, 21, 21));
        label_56->setFont(font);
        TrainSpdDiffLineEdit_2 = new SlGfwLineEdit(groupBox_6);
        TrainSpdDiffLineEdit_2->setObjectName(QString::fromUtf8("TrainSpdDiffLineEdit_2"));
        TrainSpdDiffLineEdit_2->setGeometry(QRect(30, 190, 51, 31));
        TrainSpdDiffLineEdit_2->setAlignment(Qt::AlignHCenter);
        groupBox_7 = new SlGfwGroupBox(groupBox_5);
        groupBox_7->setObjectName(QString::fromUtf8("groupBox_7"));
        groupBox_7->setGeometry(QRect(0, 160, 201, 71));
        groupBox_7->setAutoFillBackground(false);
        groupBox_7->setHmiFontSize(-5);
        groupBox_7->setCheckable(false);
        label_22 = new SlGfwLabel(groupBox_7);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(10, 0, 101, 21));
        label_22->setAutoFillBackground(false);
        label_22->setHmiFontSize(-5);
        label_22->setInverseColors(true);
        TrainSpdDiffLineEdit = new SlGfwLineEdit(groupBox_7);
        TrainSpdDiffLineEdit->setObjectName(QString::fromUtf8("TrainSpdDiffLineEdit"));
        TrainSpdDiffLineEdit->setGeometry(QRect(10, 40, 51, 24));
        TrainSpdDiffLineEdit->setHmiFonts(true);
        TrainSpdDiffLineEdit->setHmiFontSize(0);
        TrainSpdDiffLineEdit->setAlignment(Qt::AlignHCenter);
        label_26 = new SlGfwLabel(groupBox_7);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(110, 20, 41, 25));
        label_26->setHmiFontSize(-5);
        label_57 = new SlGfwLabel(groupBox_7);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(214, 41, 31, 25));
        label_57->setHmiFontSize(-5);
        TrainSpdDiffTimeLineEdit = new SlGfwLineEdit(groupBox_7);
        TrainSpdDiffTimeLineEdit->setObjectName(QString::fromUtf8("TrainSpdDiffTimeLineEdit"));
        TrainSpdDiffTimeLineEdit->setGeometry(QRect(110, 40, 51, 24));
        TrainSpdDiffTimeLineEdit->setHmiFonts(true);
        TrainSpdDiffTimeLineEdit->setHmiFontSize(0);
        TrainSpdDiffTimeLineEdit->setAlignment(Qt::AlignHCenter);
        label_27 = new SlGfwLabel(groupBox_7);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(30, 20, 41, 25));
        label_27->setHmiFontSize(-5);
        label_28 = new SlGfwLabel(groupBox_7);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(70, 40, 31, 25));
        label_28->setHmiFontSize(-5);
        label_47 = new SlGfwLabel(groupBox_7);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(170, 40, 31, 25));
        label_47->setHmiFontSize(-5);
        H_WorkIniPosLineEdit = new SlGfwLineEdit(ParameterFormUi);
        H_WorkIniPosLineEdit->setObjectName(QString::fromUtf8("H_WorkIniPosLineEdit"));
        H_WorkIniPosLineEdit->setGeometry(QRect(462, 310, 51, 27));
        H_WorkIniPosLineEdit->setAlignment(Qt::AlignHCenter);
        V_DeviceIniPosLineEdit = new SlGfwLineEdit(ParameterFormUi);
        V_DeviceIniPosLineEdit->setObjectName(QString::fromUtf8("V_DeviceIniPosLineEdit"));
        V_DeviceIniPosLineEdit->setGeometry(QRect(182, 340, 51, 27));
        V_DeviceIniPosLineEdit->setAlignment(Qt::AlignHCenter);
        QWidget::setTabOrder(LH_CuttingDepthLineEdit, LV_CuttingDepthLineEdit);
        QWidget::setTabOrder(LV_CuttingDepthLineEdit, RH_CuttingDepthLineEdit);
        QWidget::setTabOrder(RH_CuttingDepthLineEdit, RV_CuttingDepthLineEdit);
        QWidget::setTabOrder(RV_CuttingDepthLineEdit, H_DeviceIniPosLineEdit);
        QWidget::setTabOrder(H_DeviceIniPosLineEdit, V_DeviceIniPosLineEdit);
        QWidget::setTabOrder(V_DeviceIniPosLineEdit, H_WorkIniPosLineEdit);
        QWidget::setTabOrder(H_WorkIniPosLineEdit, V_WorkIniPosLineEdit);
        QWidget::setTabOrder(V_WorkIniPosLineEdit, TrainSpeedLineEdit);
        QWidget::setTabOrder(TrainSpeedLineEdit, SlopeLengthLineEdit);
        QWidget::setTabOrder(SlopeLengthLineEdit, AxisLineSpeedLineEdit);
        QWidget::setTabOrder(AxisLineSpeedLineEdit, MillingModuleLineEdit);

        retranslateUi(ParameterFormUi);

        QMetaObject::connectSlotsByName(ParameterFormUi);
    } // setupUi

    void retranslateUi(SlGfwDialogForm *ParameterFormUi)
    {
        label_36->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_24->setStyleSheet(QApplication::translate("ParameterFormUi", "background-color: rgb(0, 0, 0);", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("ParameterFormUi", "\351\223\243\345\210\200\344\275\215\347\275\256", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label->setStyleSheet(QApplication::translate("ParameterFormUi", "background-color: rgb(255, 255, 0)", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("ParameterFormUi", "\344\275\234\344\270\232\345\217\202\346\225\260", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QString());
        label_2->setStyleSheet(QApplication::translate("ParameterFormUi", "background-color: rgb(0, 0, 0);", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("ParameterFormUi", "\345\267\246\351\223\243\345\211\212\345\215\225\345\205\203", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("ParameterFormUi", "\346\250\252\345\220\221\345\210\207\346\267\261", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("ParameterFormUi", "\345\236\202\345\220\221\345\210\207\346\267\261", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("ParameterFormUi", "\346\201\222\345\212\237\347\216\207\351\223\243\345\211\212", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("ParameterFormUi", "%", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("ParameterFormUi", "\350\243\205\347\275\256\345\236\202\345\220\221\345\210\235\345\247\213\344\275\215", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("ParameterFormUi", "\344\275\234\344\270\232\345\236\202\345\220\221\345\210\235\345\247\213\344\275\215", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("ParameterFormUi", "\350\243\205\347\275\256\346\250\252\345\220\221\345\210\235\345\247\213\344\275\215", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("ParameterFormUi", "\344\275\234\344\270\232\346\250\252\345\220\221\345\210\235\345\247\213\344\275\215", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QString());
        label_3->setStyleSheet(QApplication::translate("ParameterFormUi", "background-color: rgb(0, 0, 0);", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("ParameterFormUi", "\345\217\263\351\223\243\345\211\212\345\215\225\345\205\203", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("ParameterFormUi", "\346\250\252\345\220\221\345\210\207\346\267\261", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("ParameterFormUi", "\345\236\202\345\220\221\345\210\207\346\267\261", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("ParameterFormUi", "%", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("ParameterFormUi", "\346\201\222\345\212\237\347\216\207\351\223\243\345\211\212", 0, QApplication::UnicodeUTF8));
        groupBox_5->setStyleSheet(QString());
        label_37->setText(QApplication::translate("ParameterFormUi", "\351\241\272\345\235\241\351\225\277\345\272\246", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("ParameterFormUi", "Km/h", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("ParameterFormUi", "\350\275\246     \351\200\237", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("ParameterFormUi", "\345\210\207\345\211\212\347\272\277\351\200\237\345\272\246", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("ParameterFormUi", "m/min", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("ParameterFormUi", "\350\275\246\350\276\206\347\273\204\345\220\210", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("ParameterFormUi", "module", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("ParameterFormUi", "\346\201\222\345\212\237\347\216\207\351\223\243\345\211\212", 0, QApplication::UnicodeUTF8));
        groupBox_6->setStyleSheet(QString());
        label_46->setText(QApplication::translate("ParameterFormUi", "\351\241\272\345\235\241\351\225\277\345\272\246", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("ParameterFormUi", "Km/h", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("ParameterFormUi", "\350\275\246     \351\200\237", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("ParameterFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("ParameterFormUi", "\345\210\207\345\211\212\347\272\277\351\200\237\345\272\246", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("ParameterFormUi", "m/min", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("ParameterFormUi", "\350\275\246\350\276\206\347\273\204\345\220\210", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("ParameterFormUi", "module", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("ParameterFormUi", "\346\201\222\345\212\237\347\216\207\351\223\243\345\211\212", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("ParameterFormUi", "%", 0, QApplication::UnicodeUTF8));
        groupBox_7->setTitle(QString());
        label_22->setStyleSheet(QApplication::translate("ParameterFormUi", "background-color: rgb(0, 0, 0);", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("ParameterFormUi", "\346\234\200\345\244\247\351\200\237\345\272\246\350\256\276\347\275\256", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("ParameterFormUi", "\346\227\266\351\227\264", 0, QApplication::UnicodeUTF8));
        label_57->setText(QApplication::translate("ParameterFormUi", "ms", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("ParameterFormUi", "\351\200\237\345\272\246", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("ParameterFormUi", "% x", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("ParameterFormUi", "ms", 0, QApplication::UnicodeUTF8));
        Q_UNUSED(ParameterFormUi);
    } // retranslateUi

};

namespace Ui {
    class ParameterFormUi: public Ui_ParameterFormUi {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_PARAMETERFORM_H
