<!DOCTYPE TS>
<TS>
   <context>
     <name>Trainmilling</name>
	<!--for m_LH_Error(PCU Error) Stage 0-->
	 <message>
        <source>Source_120000</source>
		<translation>左侧Y向电机当前值与目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120001</source>
		<translation>左侧Y向电机两次目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120002</source>
		<translation>左侧Y向两次传感器信号差值大于1.0mm</translation>
     </message>
     <message>
        <source>Source_120003</source>
		<translation>左侧Y向传感器当前值与目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120004</source>
		<translation>装置Y向跟随时自调试时间大于1.5秒</translation>
     </message>
     <message>
        <source>Source_120005</source>
		<translation>左侧测速轮速度值异常</translation>
     </message>
     <message>
        <source>Source_120006</source>
		<translation>左侧主轴电机功率过载</translation>
     </message>
     <message>
        <source>Source_120007</source>
		<translation>左侧Y向传感器异常</translation>
     </message>
     <message>
        <source>Source_120008</source>
		<translation>左侧Y向电机碰到软限位</translation>
     </message>
     <message>
        <source>Source_120009</source>
		<translation>左侧主轴转速偏离设定值</translation>
     </message>
     <message>
        <source>Source_120010</source>
		<translation>列车速度偏离设定值</translation>
     </message>
	 
	 <!--for m_LV_Error(PCU Error) Stage 0-->
	 <message>
        <source>Source_120100</source>
		<translation>左侧Z向电机当前值与目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120101</source>
		<translation>左侧Z向电机两次目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120102</source>
		<translation>左侧Z向两次传感器信号差值大于1.0mm</translation>
     </message>
     <message>
        <source>Source_120103</source>
		<translation>左侧Z向传感器当前值与目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120104</source>
		<translation>装置Y向跟随时自调试时间大于1.5秒</translation>
     </message>
     <message>
        <source>Source_120105</source>
		<translation>左侧测速轮速度值异常</translation>
     </message>
     <message>
        <source>Source_120106</source>
		<translation>左侧主轴电机功率过载</translation>
     </message>
     <message>
        <source>Source_120107</source>
		<translation>左侧Z向传感器异常</translation>
     </message>
     <message>
        <source>Source_120108</source>
		<translation>左侧Z向电机碰到软限位</translation>
     </message>
     <message>
        <source>Source_120109</source>
		<translation>左侧主轴转速偏离设定值</translation>
     </message>
	 
	<!--for m_RH_Error(PCU Error) Stage 0-->
	 <message>
        <source>Source_120200</source>
		<translation>右侧Y向电机当前值与目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120201</source>
		<translation>右侧Y向电机两次目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120202</source>
		<translation>右侧Y向两次传感器信号差值大于1.0mm</translation>
     </message>
     <message>
        <source>Source_120203</source>
		<translation>右侧Y向传感器当前值与目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120204</source>
		<translation>装置Y向跟随时自调试时间大于1.5秒</translation>
     </message>
     <message>
        <source>Source_120205</source>
		<translation>右侧测速轮速度值异常</translation>
     </message>
     <message>
        <source>Source_120206</source>
		<translation>右侧主轴电机功率过载</translation>
     </message> 
     <message>
        <source>Source_120207</source>
		<translation>右侧Y向传感器异常</translation>
     </message> 
     <message>
        <source>Source_120208</source>
		<translation>右侧Y向电机碰到软限位</translation>
     </message> 
     <message>
        <source>Source_120209</source>
		<translation>右侧主轴转速偏离设定值</translation>
     </message> 
	 
	<!--for m_RV_Error(PCU Error) Stage 0-->
	 <message>
        <source>Source_120300</source>
		<translation>右侧Z向电机当前值与目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120301</source>
		<translation>右侧Z向电机两次目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120302</source>
		<translation>右侧Z向两次传感器信号差值大于1.0mm</translation>
     </message>
     <message>
        <source>Source_120303</source>
		<translation>右侧Z向传感器当前值与目标值差值大于3mm</translation>
     </message>
     <message>
        <source>Source_120304</source>
		<translation>装置Y向跟随时自调试时间大于1.5秒</translation>
     </message>
     <message>
        <source>Source_120305</source>
		<translation>右侧测速轮速度值异常</translation>
     </message>
     <message>
        <source>Source_120306</source>
		<translation>右侧主轴电机功率过载</translation>
     </message>
     <message>
        <source>Source_120307</source>
		<translation>右侧Z向传感器异常</translation>
     </message>
     <message>
        <source>Source_120308</source>
		<translation>右侧Z向电机碰到软限位</translation>
     </message>
     <message>
        <source>Source_120309</source>
		<translation>右侧主轴转速偏离设定值</translation>
     </message>
	 
	<!--for PLC Error-->	 
     <message>
        <source>Source_130000</source>
		<translation>NC伺服系统故障(系统错误)</translation>
     </message>
     <message>
        <source>Source_130001</source>
		<translation>按钮在该阶段无效</translation>
     </message>
     <message>
        <source>Source_130002</source>
		<translation>左液压锁故障</translation>
     </message>
     <message>
        <source>Source_130003</source>
		<translation>右液压锁故障</translation>
     </message>
     <message>
        <source>Source_130004</source>
		<translation>左液压比例减压阀故障</translation>
     </message>
     <message>
        <source>Source_130005</source>
		<translation>右液压比例减压阀故障</translation>
     </message>
     <message>
        <source>Source_130006</source>
		<translation>左侧集屑仓压力异常</translation>
     </message>
     <message>
        <source>Source_130007</source>
		<translation>右侧集屑仓压力异常</translation>
     </message>
     <message>
        <source>Source_130008</source>
		<translation>TC01变压器供电过载</translation>
     </message>
     <message>
        <source>Source_130009</source>
		<translation>TC02变压器供电过载</translation>
     </message>
     <message>
        <source>Source_130010</source>
		<translation>TC03变压器供电过载</translation>
     </message>
     <message>
        <source>Source_130011</source>
		<translation>110V供电过载</translation>
     </message>
     <message>
        <source>Source_130012</source>
		<translation>控制柜空调供电过载</translation>
     </message>
     <message>
        <source>Source_130013</source>
		<translation>加热器供电过载</translation>
     </message>
     <message>
        <source>Source_130014</source>
		<translation>系统24V电源过载</translation>
     </message>
     <message>
        <source>Source_130015</source>
		<translation>电磁阀24V电源过载</translation>
     </message>
     <message>
        <source>Source_130016</source>
		<translation>输入输出24V电源过载</translation>
     </message>
     <message>
        <source>Source_130017</source>
		<translation>左侧主轴电机风扇过载</translation>
     </message>
     <message>
        <source>Source_130018</source>
		<translation>右侧主轴电机风扇过载</translation>
     </message>
     <message>
        <source>Source_130019</source>
		<translation>液压动力包过载</translation>
     </message>
     <message>
        <source>Source_130020</source>
		<translation>左侧集屑离心风机过载</translation>
     </message>
     <message>
        <source>Source_130021</source>
		<translation>左侧打磨电机过载</translation>
     </message>
     <message>
        <source>Source_130022</source>
		<translation>UPS电源供电过载</translation>
     </message>
     <message>
        <source>Source_130023</source>
		<translation>电器间通风电机过载</translation>
     </message>
     <message>
        <source>Source_130024</source>
		<translation>制动模块1故障</translation>
     </message>
     <message>
        <source>Source_130025</source>
		<translation>制动模块2故障</translation>
     </message>
     <message>
        <source>Source_130026</source>
		<translation>左侧排屑电机过载</translation>
     </message>
     <message>
        <source>Source_130027</source>
		<translation>右侧排屑电机过载</translation>
     </message>
     <message>
        <source>Source_130028</source>
		<translation>右侧集屑离心风机过载</translation>
     </message>
     <message>
        <source>Source_130029</source>
		<translation>右侧打磨电机过载</translation>
     </message>
     <message>
        <source>Source_130030</source>
		<translation>监控系统过载</translation>
     </message>
     <message>
        <source>Source_130031</source>
		<translation>左侧排屑急停</translation>
     </message>
     <message>
        <source>Source_130032</source>
		<translation>右侧排屑急停</translation>
     </message>
     <message>
        <source>Source_130033</source>
		<translation>系统急停</translation>
     </message>
     <message>
        <source>Source_130034</source>
		<translation>左侧轨廓扫描测距仪故障</translation>
     </message>
     <message>
        <source>Source_130035</source>
		<translation>右侧轨廓扫描测距仪故障</translation>
     </message>
     <message>
        <source>Source_130036</source>
		<translation>左侧抱闸通</translation>
     </message>
     <message>
        <source>Source_130037</source>
		<translation>右侧抱闸通</translation>
     </message>
     <message>
        <source>Source_130038</source>
		<translation>车箱 满报警（左1）</translation>
     </message>
     <message>
        <source>Source_130039</source>
		<translation>车箱 满报警（左2）</translation>
     </message>
     <message>
        <source>Source_130040</source>
		<translation>车箱 满报警（左3）</translation>
     </message>
     <message>
        <source>Source_130041</source>
		<translation>车箱 满报警（右1）</translation>
     </message>
     <message>
        <source>Source_130042</source>
		<translation>车箱 满报警（右2）</translation>
     </message>
     <message>
        <source>Source_130043</source>
		<translation>车箱 满报警（右3）</translation>
     </message>
     <message>
        <source>Source_130044</source>
		<translation>左侧皮带断裂</translation>
     </message>
     <message>
        <source>Source_130045</source>
		<translation>右侧皮带断裂</translation>
     </message>
     <message>
        <source>Source_130046</source>
		<translation>整机碰撞故障</translation>
     </message>
     <message>
        <source>Source_130047</source>
		<translation>左侧打磨急停</translation>
     </message>
     <message>
        <source>Source_130048</source>
		<translation>右侧打磨急停</translation>
     </message>
     <message>
        <source>Source_130049</source>
		<translation>左侧测距仪LY1故障</translation>
     </message>
     <message>
        <source>Source_130050</source>
		<translation>左侧测距仪LY2故障</translation>
     </message>
     <message>
        <source>Source_130051</source>
		<translation>左侧测距仪LZ1故障</translation>
     </message>
     <message>
        <source>Source_130052</source>
		<translation>左侧测距仪LZ2故障</translation>
     </message>
     <message>
        <source>Source_130053</source>
		<translation>右侧测距仪RY1故障</translation>
     </message>
     <message>
        <source>Source_130054</source>
		<translation>右侧测距仪RY2故障</translation>
     </message>
     <message>
        <source>Source_130055</source>
		<translation>右侧测距仪RZ1故障</translation>
     </message>
     <message>
        <source>Source_130056</source>
		<translation>右侧测距仪RZ2故障</translation>
     </message>
     <message>
        <source>Source_130057</source>
		<translation>比例阀放大器状态监控故障</translation>
     </message>
     <message>
        <source>Source_130058</source>
		<translation>液压站液压油位报警</translation>
     </message>
     <message>
        <source>Source_130059</source>
		<translation>液压站液压油位停机</translation>
     </message>
     <message>
        <source>Source_130060</source>
		<translation>液压站压力管路过滤器报警</translation>
     </message>     
	 <message>
        <source>Source_130061</source>
		<translation>液压站回油过滤器报警</translation>
     </message>
     <message>
        <source>Source_130062</source>
		<translation>液压站液压油温低预警</translation>
     </message>     
	 <message>
        <source>Source_130063</source>
		<translation>液压站液压油温高预警</translation>
     </message>
	 <message>
        <source>Source_130064</source>
		<translation>作业车控权使能无效</translation>
     </message>
	 <message>
        <source>Source_130065</source>
		<translation>铣磨作业工况使能无效</translation>
     </message>
	 <message>
        <source>Source_130066</source>
		<translation>液压比例阀放大器故障</translation>
     </message>
	 
	 <!--for other Error-->	 
	 <message>
        <source>Source_140000</source>
		<translation>磁盘空间不够，请及时清理</translation>
     </message>
	<message>
        <source>Source_140001</source>
		<translation>该系统未获得授权，不能运行</translation>
     </message> 
	<message>
        <source>Source_140002</source>
		<translation>铣削控制系统与机车通信故障</translation>
     </message> 
	<message>
        <source>Source_140003</source>
		<translation>铣削控制系统内部通信故障</translation>
     </message> 
	<message>
        <source>Source_140004</source>
		<translation>状态异常，系统执行顺坡切出</translation>
     </message> 
	 </context>
</TS>
