/********************************************************************************
** Form generated from reading ui file 'statusform.ui'
**
** Created: Mon Dec 16 13:29:51 2019
**      by: Qt User Interface Compiler version 4.5.2
**
** WARNING! All changes made in this file will be lost when recompiling ui file!
********************************************************************************/

#ifndef UI_STATUSFORM_H
#define UI_STATUSFORM_H

#include <QtCore/QLocale>
#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QProgressBar>
#include "slgfwdialogform.h"
#include "slgfwgroupbox.h"
#include "slgfwlabel.h"
#include "slgfwlineedit.h"

QT_BEGIN_NAMESPACE

class Ui_StatusFormUi
{
public:
    SlGfwLabel *label;
    SlGfwLabel *label_29;
    SlGfwLabel *label_35;
    SlGfwGroupBox *groupBox;
    SlGfwLabel *label_2;
    SlGfwLabel *label_6;
    SlGfwLineEdit *L_TemparatureLineEdit;
    SlGfwLabel *label_7;
    SlGfwLineEdit *R_TemparatureLineEdit;
    SlGfwLabel *label_8;
    SlGfwLabel *label_3;
    QProgressBar *L_PowerProgressBar;
    QProgressBar *R_PowerProgressBar;
    SlGfwLabel *label_9;
    SlGfwLabel *label_10;
    SlGfwLabel *LV_SensorLabel1;
    SlGfwLabel *LH_SensorLabel1;
    SlGfwLabel *LH_SensorLabel2;
    SlGfwLabel *LV_SensorLabel2;
    SlGfwLabel *RH_SensorLabel2;
    SlGfwLabel *RV_SensorLabel2;
    SlGfwLabel *RV_SensorLabel1;
    SlGfwLabel *RH_SensorLabel1;
    SlGfwLabel *label_19;
    SlGfwLabel *label_20;
    SlGfwLineEdit *L_MillingLengthLineEdit;
    SlGfwLineEdit *R_MillingLengthLineEdit;
    SlGfwLabel *label_42;
    SlGfwLabel *label_43;
    SlGfwGroupBox *groupBox_2;
    SlGfwLabel *label_45;
    SlGfwLabel *label_23;
    SlGfwLineEdit *LH_MotorDistToGoLineEdit;
    SlGfwLabel *label_26;
    SlGfwLineEdit *RV_MotorCurPosLineEdit;
    SlGfwLineEdit *LV_MotorCurPosLineEdit;
    SlGfwLineEdit *LH_SensorValueLineEdit1;
    SlGfwLabel *label_25;
    SlGfwLineEdit *LH_MotorCurPosLineEdit;
    SlGfwLineEdit *RV_SensorValueLineEdit1;
    SlGfwLineEdit *RH_MotorDistToGoLineEdit;
    SlGfwLineEdit *RH_MotorCurPosLineEdit;
    SlGfwLineEdit *LV_MotorDistToGoLineEdit;
    SlGfwLabel *label_22;
    SlGfwLabel *label_46;
    SlGfwLabel *label_44;
    SlGfwLineEdit *RH_SensorValueLineEdit1;
    SlGfwLineEdit *LV_SensorValueLineEdit1;
    SlGfwLineEdit *RV_MotorDistToGoLineEdit;
    SlGfwLineEdit *R_AxisAngularSpeedLineEdit;
    SlGfwLineEdit *L_AxisAngularSpeedLineEdit;
    SlGfwLabel *label_27;
    SlGfwLabel *label_47;
    SlGfwLabel *label_48;
    SlGfwLabel *label_40;
    SlGfwLineEdit *LV_SensorValueLineEdit2;
    SlGfwLineEdit *RH_SensorValueLineEdit2;
    SlGfwLineEdit *LH_SensorValueLineEdit2;
    SlGfwLineEdit *RV_SensorValueLineEdit2;
    SlGfwLineEdit *RV_SoftShoeLineEdit;
    SlGfwLabel *label_55;
    SlGfwLineEdit *RH_SoftShoeLineEdit;
    SlGfwLineEdit *LV_SoftShoeLineEdit;
    SlGfwLineEdit *LH_SoftShoeLineEdit;
    SlGfwLineEdit *LV_TargetValueLineEdit;
    SlGfwLabel *label_56;
    SlGfwLineEdit *LH_TargetValueLineEdit;
    SlGfwLineEdit *RH_TargetValueLineEdit;
    SlGfwLineEdit *RV_TargetValueLineEdit;
    SlGfwLineEdit *LH_CutBiasLineEdit;
    SlGfwLineEdit *LV_CutBiasLineEdit;
    SlGfwLabel *label_28;
    SlGfwLabel *label_31;
    SlGfwLabel *label_33;
    SlGfwLineEdit *RV_CutBiasLineEdit;
    SlGfwLabel *label_34;
    SlGfwLineEdit *RH_CutBiasLineEdit;
    SlGfwLabel *L_PressShoeLabel;
    SlGfwLabel *label_11;
    SlGfwLabel *R_PressShoeLabel;
    SlGfwLabel *label_12;
    SlGfwLabel *label_49;
    SlGfwLabel *label_21;
    SlGfwLineEdit *L_HydraulicTransmitterLineEdit;
    SlGfwLabel *label_41;
    SlGfwLineEdit *R_HydraulicTransmitterLineEdit;
    SlGfwLabel *label_51;
    SlGfwLineEdit *WorkStatusLineEdit;
    SlGfwLabel *label_54;
    SlGfwLineEdit *L_SMWPosLineEdit;
    SlGfwLabel *label_57;
    SlGfwLabel *label_58;
    SlGfwLineEdit *R_SMWPosLineEdit;
    SlGfwLabel *label_59;
    SlGfwLabel *label_60;
    SlGfwLabel *label_61;
    SlGfwLineEdit *ShineStatusLineEdit;
    SlGfwLabel *L_CollectorBinLabel;
    SlGfwLabel *TrainCommLabel;
    SlGfwLabel *label_30;
    SlGfwLabel *label_36;
    SlGfwLabel *CH1NCLabel;
    SlGfwLabel *GrindLabel;
    SlGfwLabel *label_32;
    SlGfwLabel *label_37;
    SlGfwLabel *CH2NCLabel;
    SlGfwLabel *LockLabel;
    SlGfwLabel *BogyLabel;
    SlGfwLabel *label_39;
    SlGfwLabel *R_CollectorBinLabel;
    SlGfwLabel *label_38;
    SlGfwLabel *label_50;
    SlGfwLabel *label_24;
    SlGfwLineEdit *L_SMWSpeedLineEdit;
    SlGfwLabel *label_52;
    SlGfwLineEdit *R_SMWSpeedLineEdit;
    SlGfwLabel *label_53;
    SlGfwLabel *ControlModeLabel;

    void setupUi(SlGfwDialogForm *StatusFormUi)
    {
        if (StatusFormUi->objectName().isEmpty())
            StatusFormUi->setObjectName(QString::fromUtf8("StatusFormUi"));
        StatusFormUi->resize(570, 373);
        StatusFormUi->setFocusPolicy(Qt::NoFocus);
        label = new SlGfwLabel(StatusFormUi);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(210, 22, 171, 35));
        QFont font;
        font.setFamily(QString::fromUtf8("Siemens AD CH Simplified"));
        font.setBold(false);
        font.setWeight(50);
        label->setFont(font);
        label->setAutoFillBackground(false);
        label->setAlignment(Qt::AlignCenter);
        label_29 = new SlGfwLabel(StatusFormUi);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(10, 320, 71, 31));
        label_35 = new SlGfwLabel(StatusFormUi);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 345, 71, 31));
        groupBox = new SlGfwGroupBox(StatusFormUi);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(-18, 58, 620, 260));
        groupBox->setAutoFillBackground(false);
        groupBox->setHmiFonts(true);
        groupBox->setHmiColors(true);
        groupBox->setNavigationMode(true);
        groupBox->setHmiUseBigFont(false);
        groupBox->setHmiFontSize(12);
        groupBox->setFlat(false);
        groupBox->setCheckable(false);
        label_2 = new SlGfwLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(20, 0, 81, 21));
        label_2->setFont(font);
        label_2->setAutoFillBackground(false);
        label_2->setHmiFonts(true);
        label_2->setHmiColors(true);
        label_2->setInverseColors(true);
        label_6 = new SlGfwLabel(groupBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(24, 90, 81, 20));
        L_TemparatureLineEdit = new SlGfwLineEdit(groupBox);
        L_TemparatureLineEdit->setObjectName(QString::fromUtf8("L_TemparatureLineEdit"));
        L_TemparatureLineEdit->setGeometry(QRect(218, 30, 51, 20));
        L_TemparatureLineEdit->setAlignment(Qt::AlignLeading);
        L_TemparatureLineEdit->setReadOnly(true);
        label_7 = new SlGfwLabel(groupBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(286, 30, 30, 20));
        R_TemparatureLineEdit = new SlGfwLineEdit(groupBox);
        R_TemparatureLineEdit->setObjectName(QString::fromUtf8("R_TemparatureLineEdit"));
        R_TemparatureLineEdit->setGeometry(QRect(324, 30, 51, 20));
        R_TemparatureLineEdit->setAlignment(Qt::AlignLeading);
        R_TemparatureLineEdit->setReadOnly(true);
        label_8 = new SlGfwLabel(groupBox);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(24, 119, 81, 20));
        label_3 = new SlGfwLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(500, 1, 81, 21));
        label_3->setAutoFillBackground(false);
        label_3->setInverseColors(true);
        L_PowerProgressBar = new QProgressBar(groupBox);
        L_PowerProgressBar->setObjectName(QString::fromUtf8("L_PowerProgressBar"));
        L_PowerProgressBar->setGeometry(QRect(22, 15, 180, 45));
        QFont font1;
        font1.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font1.setPointSize(14);
        font1.setBold(true);
        font1.setItalic(false);
        font1.setUnderline(false);
        font1.setWeight(75);
        font1.setStrikeOut(false);
        L_PowerProgressBar->setFont(font1);
        L_PowerProgressBar->setAutoFillBackground(false);
        L_PowerProgressBar->setLocale(QLocale(QLocale::Chinese, QLocale::China));
        L_PowerProgressBar->setNavigationMode(true);
        L_PowerProgressBar->setValue(0);
        L_PowerProgressBar->setAlignment(Qt::AlignCenter);
        L_PowerProgressBar->setInvertedAppearance(false);
        R_PowerProgressBar = new QProgressBar(groupBox);
        R_PowerProgressBar->setObjectName(QString::fromUtf8("R_PowerProgressBar"));
        R_PowerProgressBar->setGeometry(QRect(392, 15, 180, 45));
        QFont font2;
        font2.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font2.setPointSize(14);
        font2.setBold(true);
        font2.setItalic(false);
        font2.setUnderline(false);
        font2.setWeight(75);
        font2.setStrikeOut(false);
        font2.setKerning(true);
        R_PowerProgressBar->setFont(font2);
        R_PowerProgressBar->setContextMenuPolicy(Qt::DefaultContextMenu);
        R_PowerProgressBar->setLocale(QLocale(QLocale::Chinese, QLocale::China));
        R_PowerProgressBar->setValue(0);
        R_PowerProgressBar->setAlignment(Qt::AlignCenter);
        label_9 = new SlGfwLabel(groupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(494, 119, 80, 20));
        label_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_10 = new SlGfwLabel(groupBox);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(494, 90, 80, 25));
        label_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LV_SensorLabel1 = new SlGfwLabel(groupBox);
        LV_SensorLabel1->setObjectName(QString::fromUtf8("LV_SensorLabel1"));
        LV_SensorLabel1->setGeometry(QRect(110, 119, 20, 20));
        LH_SensorLabel1 = new SlGfwLabel(groupBox);
        LH_SensorLabel1->setObjectName(QString::fromUtf8("LH_SensorLabel1"));
        LH_SensorLabel1->setGeometry(QRect(110, 90, 20, 20));
        LH_SensorLabel2 = new SlGfwLabel(groupBox);
        LH_SensorLabel2->setObjectName(QString::fromUtf8("LH_SensorLabel2"));
        LH_SensorLabel2->setGeometry(QRect(130, 90, 20, 20));
        LV_SensorLabel2 = new SlGfwLabel(groupBox);
        LV_SensorLabel2->setObjectName(QString::fromUtf8("LV_SensorLabel2"));
        LV_SensorLabel2->setGeometry(QRect(130, 119, 20, 20));
        RH_SensorLabel2 = new SlGfwLabel(groupBox);
        RH_SensorLabel2->setObjectName(QString::fromUtf8("RH_SensorLabel2"));
        RH_SensorLabel2->setGeometry(QRect(440, 90, 20, 20));
        RV_SensorLabel2 = new SlGfwLabel(groupBox);
        RV_SensorLabel2->setObjectName(QString::fromUtf8("RV_SensorLabel2"));
        RV_SensorLabel2->setGeometry(QRect(440, 119, 20, 20));
        RV_SensorLabel1 = new SlGfwLabel(groupBox);
        RV_SensorLabel1->setObjectName(QString::fromUtf8("RV_SensorLabel1"));
        RV_SensorLabel1->setGeometry(QRect(460, 119, 20, 20));
        RH_SensorLabel1 = new SlGfwLabel(groupBox);
        RH_SensorLabel1->setObjectName(QString::fromUtf8("RH_SensorLabel1"));
        RH_SensorLabel1->setGeometry(QRect(460, 90, 20, 20));
        label_19 = new SlGfwLabel(groupBox);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(24, 167, 81, 20));
        label_20 = new SlGfwLabel(groupBox);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(494, 167, 80, 20));
        label_20->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        L_MillingLengthLineEdit = new SlGfwLineEdit(groupBox);
        L_MillingLengthLineEdit->setObjectName(QString::fromUtf8("L_MillingLengthLineEdit"));
        L_MillingLengthLineEdit->setGeometry(QRect(95, 167, 48, 20));
        L_MillingLengthLineEdit->setAlignment(Qt::AlignLeading);
        L_MillingLengthLineEdit->setReadOnly(true);
        R_MillingLengthLineEdit = new SlGfwLineEdit(groupBox);
        R_MillingLengthLineEdit->setObjectName(QString::fromUtf8("R_MillingLengthLineEdit"));
        R_MillingLengthLineEdit->setGeometry(QRect(451, 167, 48, 20));
        R_MillingLengthLineEdit->setAlignment(Qt::AlignLeading);
        R_MillingLengthLineEdit->setReadOnly(true);
        label_42 = new SlGfwLabel(groupBox);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(146, 167, 21, 20));
        label_43 = new SlGfwLabel(groupBox);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(430, 167, 20, 20));
        groupBox_2 = new SlGfwGroupBox(groupBox);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(163, 52, 266, 208));
        label_45 = new SlGfwLabel(groupBox_2);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(225, 11, 41, 20));
        label_23 = new SlGfwLabel(groupBox_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(99, 136, 66, 20));
        label_23->setAlignment(Qt::AlignCenter);
        LH_MotorDistToGoLineEdit = new SlGfwLineEdit(groupBox_2);
        LH_MotorDistToGoLineEdit->setObjectName(QString::fromUtf8("LH_MotorDistToGoLineEdit"));
        LH_MotorDistToGoLineEdit->setGeometry(QRect(2, 159, 48, 20));
        LH_MotorDistToGoLineEdit->setReadOnly(true);
        label_26 = new SlGfwLabel(groupBox_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(99, 39, 66, 20));
        label_26->setAlignment(Qt::AlignCenter);
        RV_MotorCurPosLineEdit = new SlGfwLineEdit(groupBox_2);
        RV_MotorCurPosLineEdit->setObjectName(QString::fromUtf8("RV_MotorCurPosLineEdit"));
        RV_MotorCurPosLineEdit->setGeometry(QRect(214, 136, 48, 20));
        RV_MotorCurPosLineEdit->setReadOnly(true);
        LV_MotorCurPosLineEdit = new SlGfwLineEdit(groupBox_2);
        LV_MotorCurPosLineEdit->setObjectName(QString::fromUtf8("LV_MotorCurPosLineEdit"));
        LV_MotorCurPosLineEdit->setGeometry(QRect(53, 136, 48, 20));
        LV_MotorCurPosLineEdit->setAlignment(Qt::AlignLeading);
        LV_MotorCurPosLineEdit->setReadOnly(true);
        LH_SensorValueLineEdit1 = new SlGfwLineEdit(groupBox_2);
        LH_SensorValueLineEdit1->setObjectName(QString::fromUtf8("LH_SensorValueLineEdit1"));
        LH_SensorValueLineEdit1->setGeometry(QRect(2, 39, 48, 20));
        LH_SensorValueLineEdit1->setReadOnly(true);
        label_25 = new SlGfwLabel(groupBox_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(99, 159, 66, 20));
        label_25->setAlignment(Qt::AlignCenter);
        LH_MotorCurPosLineEdit = new SlGfwLineEdit(groupBox_2);
        LH_MotorCurPosLineEdit->setObjectName(QString::fromUtf8("LH_MotorCurPosLineEdit"));
        LH_MotorCurPosLineEdit->setGeometry(QRect(2, 136, 48, 20));
        LH_MotorCurPosLineEdit->setReadOnly(true);
        RV_SensorValueLineEdit1 = new SlGfwLineEdit(groupBox_2);
        RV_SensorValueLineEdit1->setObjectName(QString::fromUtf8("RV_SensorValueLineEdit1"));
        RV_SensorValueLineEdit1->setGeometry(QRect(214, 39, 48, 20));
        RV_SensorValueLineEdit1->setReadOnly(true);
        RH_MotorDistToGoLineEdit = new SlGfwLineEdit(groupBox_2);
        RH_MotorDistToGoLineEdit->setObjectName(QString::fromUtf8("RH_MotorDistToGoLineEdit"));
        RH_MotorDistToGoLineEdit->setGeometry(QRect(163, 159, 48, 20));
        RH_MotorDistToGoLineEdit->setAlignment(Qt::AlignLeading);
        RH_MotorDistToGoLineEdit->setReadOnly(true);
        RH_MotorCurPosLineEdit = new SlGfwLineEdit(groupBox_2);
        RH_MotorCurPosLineEdit->setObjectName(QString::fromUtf8("RH_MotorCurPosLineEdit"));
        RH_MotorCurPosLineEdit->setGeometry(QRect(163, 136, 48, 20));
        RH_MotorCurPosLineEdit->setAlignment(Qt::AlignLeading);
        RH_MotorCurPosLineEdit->setReadOnly(true);
        LV_MotorDistToGoLineEdit = new SlGfwLineEdit(groupBox_2);
        LV_MotorDistToGoLineEdit->setObjectName(QString::fromUtf8("LV_MotorDistToGoLineEdit"));
        LV_MotorDistToGoLineEdit->setGeometry(QRect(53, 159, 48, 20));
        LV_MotorDistToGoLineEdit->setAlignment(Qt::AlignLeading);
        LV_MotorDistToGoLineEdit->setReadOnly(true);
        label_22 = new SlGfwLabel(groupBox_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(168, 11, 41, 20));
        label_46 = new SlGfwLabel(groupBox_2);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(55, 11, 41, 20));
        label_44 = new SlGfwLabel(groupBox_2);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(11, 11, 41, 20));
        RH_SensorValueLineEdit1 = new SlGfwLineEdit(groupBox_2);
        RH_SensorValueLineEdit1->setObjectName(QString::fromUtf8("RH_SensorValueLineEdit1"));
        RH_SensorValueLineEdit1->setGeometry(QRect(163, 39, 48, 20));
        RH_SensorValueLineEdit1->setAlignment(Qt::AlignLeading);
        RH_SensorValueLineEdit1->setReadOnly(true);
        LV_SensorValueLineEdit1 = new SlGfwLineEdit(groupBox_2);
        LV_SensorValueLineEdit1->setObjectName(QString::fromUtf8("LV_SensorValueLineEdit1"));
        LV_SensorValueLineEdit1->setGeometry(QRect(53, 39, 48, 20));
        LV_SensorValueLineEdit1->setAlignment(Qt::AlignLeading);
        LV_SensorValueLineEdit1->setReadOnly(true);
        RV_MotorDistToGoLineEdit = new SlGfwLineEdit(groupBox_2);
        RV_MotorDistToGoLineEdit->setObjectName(QString::fromUtf8("RV_MotorDistToGoLineEdit"));
        RV_MotorDistToGoLineEdit->setGeometry(QRect(214, 159, 48, 20));
        RV_MotorDistToGoLineEdit->setReadOnly(true);
        R_AxisAngularSpeedLineEdit = new SlGfwLineEdit(groupBox_2);
        R_AxisAngularSpeedLineEdit->setObjectName(QString::fromUtf8("R_AxisAngularSpeedLineEdit"));
        R_AxisAngularSpeedLineEdit->setGeometry(QRect(163, 182, 48, 20));
        R_AxisAngularSpeedLineEdit->setAlignment(Qt::AlignLeading);
        R_AxisAngularSpeedLineEdit->setReadOnly(true);
        L_AxisAngularSpeedLineEdit = new SlGfwLineEdit(groupBox_2);
        L_AxisAngularSpeedLineEdit->setObjectName(QString::fromUtf8("L_AxisAngularSpeedLineEdit"));
        L_AxisAngularSpeedLineEdit->setGeometry(QRect(53, 182, 48, 20));
        L_AxisAngularSpeedLineEdit->setAlignment(Qt::AlignLeading);
        L_AxisAngularSpeedLineEdit->setReadOnly(true);
        label_27 = new SlGfwLabel(groupBox_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(99, 182, 66, 20));
        label_27->setAlignment(Qt::AlignCenter);
        label_47 = new SlGfwLabel(groupBox_2);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(2, 182, 48, 20));
        label_47->setAlignment(Qt::AlignCenter);
        label_48 = new SlGfwLabel(groupBox_2);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(214, 182, 48, 20));
        label_48->setAlignment(Qt::AlignCenter);
        label_40 = new SlGfwLabel(groupBox_2);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(99, 64, 66, 20));
        label_40->setAlignment(Qt::AlignCenter);
        LV_SensorValueLineEdit2 = new SlGfwLineEdit(groupBox_2);
        LV_SensorValueLineEdit2->setObjectName(QString::fromUtf8("LV_SensorValueLineEdit2"));
        LV_SensorValueLineEdit2->setGeometry(QRect(53, 64, 48, 20));
        LV_SensorValueLineEdit2->setAlignment(Qt::AlignLeading);
        LV_SensorValueLineEdit2->setReadOnly(true);
        RH_SensorValueLineEdit2 = new SlGfwLineEdit(groupBox_2);
        RH_SensorValueLineEdit2->setObjectName(QString::fromUtf8("RH_SensorValueLineEdit2"));
        RH_SensorValueLineEdit2->setGeometry(QRect(163, 64, 48, 20));
        RH_SensorValueLineEdit2->setAlignment(Qt::AlignLeading);
        RH_SensorValueLineEdit2->setReadOnly(true);
        LH_SensorValueLineEdit2 = new SlGfwLineEdit(groupBox_2);
        LH_SensorValueLineEdit2->setObjectName(QString::fromUtf8("LH_SensorValueLineEdit2"));
        LH_SensorValueLineEdit2->setGeometry(QRect(2, 64, 48, 20));
        LH_SensorValueLineEdit2->setReadOnly(true);
        RV_SensorValueLineEdit2 = new SlGfwLineEdit(groupBox_2);
        RV_SensorValueLineEdit2->setObjectName(QString::fromUtf8("RV_SensorValueLineEdit2"));
        RV_SensorValueLineEdit2->setGeometry(QRect(214, 64, 48, 20));
        RV_SensorValueLineEdit2->setReadOnly(true);
        RV_SoftShoeLineEdit = new SlGfwLineEdit(groupBox_2);
        RV_SoftShoeLineEdit->setObjectName(QString::fromUtf8("RV_SoftShoeLineEdit"));
        RV_SoftShoeLineEdit->setGeometry(QRect(214, 88, 48, 20));
        RV_SoftShoeLineEdit->setReadOnly(true);
        label_55 = new SlGfwLabel(groupBox_2);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(99, 88, 66, 20));
        label_55->setAlignment(Qt::AlignCenter);
        RH_SoftShoeLineEdit = new SlGfwLineEdit(groupBox_2);
        RH_SoftShoeLineEdit->setObjectName(QString::fromUtf8("RH_SoftShoeLineEdit"));
        RH_SoftShoeLineEdit->setGeometry(QRect(163, 88, 48, 20));
        RH_SoftShoeLineEdit->setAlignment(Qt::AlignLeading);
        RH_SoftShoeLineEdit->setReadOnly(true);
        LV_SoftShoeLineEdit = new SlGfwLineEdit(groupBox_2);
        LV_SoftShoeLineEdit->setObjectName(QString::fromUtf8("LV_SoftShoeLineEdit"));
        LV_SoftShoeLineEdit->setGeometry(QRect(53, 88, 48, 20));
        LV_SoftShoeLineEdit->setAlignment(Qt::AlignLeading);
        LV_SoftShoeLineEdit->setReadOnly(true);
        LH_SoftShoeLineEdit = new SlGfwLineEdit(groupBox_2);
        LH_SoftShoeLineEdit->setObjectName(QString::fromUtf8("LH_SoftShoeLineEdit"));
        LH_SoftShoeLineEdit->setGeometry(QRect(2, 88, 48, 20));
        LH_SoftShoeLineEdit->setReadOnly(true);
        LV_TargetValueLineEdit = new SlGfwLineEdit(groupBox_2);
        LV_TargetValueLineEdit->setObjectName(QString::fromUtf8("LV_TargetValueLineEdit"));
        LV_TargetValueLineEdit->setGeometry(QRect(53, 112, 48, 20));
        LV_TargetValueLineEdit->setAlignment(Qt::AlignLeading);
        LV_TargetValueLineEdit->setReadOnly(true);
        label_56 = new SlGfwLabel(groupBox_2);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(99, 112, 66, 20));
        label_56->setAlignment(Qt::AlignCenter);
        LH_TargetValueLineEdit = new SlGfwLineEdit(groupBox_2);
        LH_TargetValueLineEdit->setObjectName(QString::fromUtf8("LH_TargetValueLineEdit"));
        LH_TargetValueLineEdit->setGeometry(QRect(2, 112, 48, 20));
        LH_TargetValueLineEdit->setReadOnly(true);
        RH_TargetValueLineEdit = new SlGfwLineEdit(groupBox_2);
        RH_TargetValueLineEdit->setObjectName(QString::fromUtf8("RH_TargetValueLineEdit"));
        RH_TargetValueLineEdit->setGeometry(QRect(163, 112, 48, 20));
        RH_TargetValueLineEdit->setAlignment(Qt::AlignLeading);
        RH_TargetValueLineEdit->setReadOnly(true);
        RV_TargetValueLineEdit = new SlGfwLineEdit(groupBox_2);
        RV_TargetValueLineEdit->setObjectName(QString::fromUtf8("RV_TargetValueLineEdit"));
        RV_TargetValueLineEdit->setGeometry(QRect(214, 112, 48, 20));
        RV_TargetValueLineEdit->setReadOnly(true);
        LH_CutBiasLineEdit = new SlGfwLineEdit(groupBox);
        LH_CutBiasLineEdit->setObjectName(QString::fromUtf8("LH_CutBiasLineEdit"));
        LH_CutBiasLineEdit->setGeometry(QRect(50, 63, 40, 20));
        LH_CutBiasLineEdit->setAlignment(Qt::AlignHCenter);
        LH_CutBiasLineEdit->setReadOnly(true);
        LV_CutBiasLineEdit = new SlGfwLineEdit(groupBox);
        LV_CutBiasLineEdit->setObjectName(QString::fromUtf8("LV_CutBiasLineEdit"));
        LV_CutBiasLineEdit->setGeometry(QRect(114, 63, 40, 20));
        LV_CutBiasLineEdit->setAlignment(Qt::AlignHCenter);
        LV_CutBiasLineEdit->setReadOnly(true);
        label_28 = new SlGfwLabel(groupBox);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(24, 63, 25, 20));
        label_31 = new SlGfwLabel(groupBox);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(95, 63, 25, 20));
        label_33 = new SlGfwLabel(groupBox);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(436, 63, 25, 20));
        RV_CutBiasLineEdit = new SlGfwLineEdit(groupBox);
        RV_CutBiasLineEdit->setObjectName(QString::fromUtf8("RV_CutBiasLineEdit"));
        RV_CutBiasLineEdit->setGeometry(QRect(533, 63, 40, 20));
        RV_CutBiasLineEdit->setAlignment(Qt::AlignHCenter);
        RV_CutBiasLineEdit->setReadOnly(true);
        label_34 = new SlGfwLabel(groupBox);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(507, 63, 25, 20));
        RH_CutBiasLineEdit = new SlGfwLineEdit(groupBox);
        RH_CutBiasLineEdit->setObjectName(QString::fromUtf8("RH_CutBiasLineEdit"));
        RH_CutBiasLineEdit->setGeometry(QRect(462, 63, 40, 20));
        RH_CutBiasLineEdit->setAlignment(Qt::AlignHCenter);
        RH_CutBiasLineEdit->setReadOnly(true);
        L_PressShoeLabel = new SlGfwLabel(groupBox);
        L_PressShoeLabel->setObjectName(QString::fromUtf8("L_PressShoeLabel"));
        L_PressShoeLabel->setGeometry(QRect(110, 145, 20, 20));
        label_11 = new SlGfwLabel(groupBox);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(24, 145, 81, 20));
        R_PressShoeLabel = new SlGfwLabel(groupBox);
        R_PressShoeLabel->setObjectName(QString::fromUtf8("R_PressShoeLabel"));
        R_PressShoeLabel->setGeometry(QRect(460, 145, 20, 20));
        label_12 = new SlGfwLabel(groupBox);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(494, 145, 80, 20));
        label_12->setInverseColors(false);
        label_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_49 = new SlGfwLabel(groupBox);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(144, 190, 21, 20));
        label_21 = new SlGfwLabel(groupBox);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(17, 190, 91, 20));
        label_21->setHmiFonts(true);
        label_21->setHmiFontSize(-4);
        L_HydraulicTransmitterLineEdit = new SlGfwLineEdit(groupBox);
        L_HydraulicTransmitterLineEdit->setObjectName(QString::fromUtf8("L_HydraulicTransmitterLineEdit"));
        L_HydraulicTransmitterLineEdit->setGeometry(QRect(95, 190, 48, 20));
        L_HydraulicTransmitterLineEdit->setAlignment(Qt::AlignLeading);
        L_HydraulicTransmitterLineEdit->setReadOnly(true);
        label_41 = new SlGfwLabel(groupBox);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(501, 190, 80, 20));
        label_41->setHmiFontSize(-4);
        R_HydraulicTransmitterLineEdit = new SlGfwLineEdit(groupBox);
        R_HydraulicTransmitterLineEdit->setObjectName(QString::fromUtf8("R_HydraulicTransmitterLineEdit"));
        R_HydraulicTransmitterLineEdit->setGeometry(QRect(451, 190, 48, 20));
        R_HydraulicTransmitterLineEdit->setAlignment(Qt::AlignLeading);
        R_HydraulicTransmitterLineEdit->setReadOnly(true);
        label_51 = new SlGfwLabel(groupBox);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(429, 190, 20, 20));
        WorkStatusLineEdit = new SlGfwLineEdit(groupBox);
        WorkStatusLineEdit->setObjectName(QString::fromUtf8("WorkStatusLineEdit"));
        WorkStatusLineEdit->setGeometry(QRect(200, 5, 101, 20));
        WorkStatusLineEdit->setAlignment(Qt::AlignHCenter);
        WorkStatusLineEdit->setReadOnly(true);
        label_54 = new SlGfwLabel(groupBox);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(130, 5, 66, 20));
        label_54->setAlignment(Qt::AlignCenter);
        L_SMWPosLineEdit = new SlGfwLineEdit(groupBox);
        L_SMWPosLineEdit->setObjectName(QString::fromUtf8("L_SMWPosLineEdit"));
        L_SMWPosLineEdit->setGeometry(QRect(81, 235, 48, 20));
        L_SMWPosLineEdit->setAlignment(Qt::AlignLeading);
        L_SMWPosLineEdit->setReadOnly(true);
        label_57 = new SlGfwLabel(groupBox);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(131, 236, 32, 20));
        label_58 = new SlGfwLabel(groupBox);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(17, 236, 91, 20));
        label_58->setHmiFontSize(-4);
        label_58->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        R_SMWPosLineEdit = new SlGfwLineEdit(groupBox);
        R_SMWPosLineEdit->setObjectName(QString::fromUtf8("R_SMWPosLineEdit"));
        R_SMWPosLineEdit->setGeometry(QRect(468, 236, 48, 20));
        R_SMWPosLineEdit->setAlignment(Qt::AlignLeading);
        R_SMWPosLineEdit->setReadOnly(true);
        label_59 = new SlGfwLabel(groupBox);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(498, 235, 80, 20));
        label_59->setHmiFontSize(-4);
        label_59->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_60 = new SlGfwLabel(groupBox);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(429, 236, 32, 20));
        label_61 = new SlGfwLabel(groupBox);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(300, 5, 66, 20));
        label_61->setAlignment(Qt::AlignCenter);
        ShineStatusLineEdit = new SlGfwLineEdit(groupBox);
        ShineStatusLineEdit->setObjectName(QString::fromUtf8("ShineStatusLineEdit"));
        ShineStatusLineEdit->setGeometry(QRect(370, 5, 101, 20));
        ShineStatusLineEdit->setAlignment(Qt::AlignHCenter);
        ShineStatusLineEdit->setReadOnly(true);
        L_CollectorBinLabel = new SlGfwLabel(StatusFormUi);
        L_CollectorBinLabel->setObjectName(QString::fromUtf8("L_CollectorBinLabel"));
        L_CollectorBinLabel->setGeometry(QRect(90, 325, 20, 20));
        TrainCommLabel = new SlGfwLabel(StatusFormUi);
        TrainCommLabel->setObjectName(QString::fromUtf8("TrainCommLabel"));
        TrainCommLabel->setGeometry(QRect(90, 350, 20, 20));
        label_30 = new SlGfwLabel(StatusFormUi);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(140, 320, 71, 31));
        label_36 = new SlGfwLabel(StatusFormUi);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(140, 345, 71, 31));
        CH1NCLabel = new SlGfwLabel(StatusFormUi);
        CH1NCLabel->setObjectName(QString::fromUtf8("CH1NCLabel"));
        CH1NCLabel->setGeometry(QRect(225, 325, 20, 20));
        GrindLabel = new SlGfwLabel(StatusFormUi);
        GrindLabel->setObjectName(QString::fromUtf8("GrindLabel"));
        GrindLabel->setGeometry(QRect(225, 350, 20, 20));
        label_32 = new SlGfwLabel(StatusFormUi);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(325, 320, 71, 31));
        label_37 = new SlGfwLabel(StatusFormUi);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(325, 345, 71, 31));
        CH2NCLabel = new SlGfwLabel(StatusFormUi);
        CH2NCLabel->setObjectName(QString::fromUtf8("CH2NCLabel"));
        CH2NCLabel->setGeometry(QRect(295, 325, 20, 20));
        LockLabel = new SlGfwLabel(StatusFormUi);
        LockLabel->setObjectName(QString::fromUtf8("LockLabel"));
        LockLabel->setGeometry(QRect(295, 350, 20, 20));
        BogyLabel = new SlGfwLabel(StatusFormUi);
        BogyLabel->setObjectName(QString::fromUtf8("BogyLabel"));
        BogyLabel->setGeometry(QRect(440, 350, 20, 20));
        label_39 = new SlGfwLabel(StatusFormUi);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(470, 320, 71, 31));
        R_CollectorBinLabel = new SlGfwLabel(StatusFormUi);
        R_CollectorBinLabel->setObjectName(QString::fromUtf8("R_CollectorBinLabel"));
        R_CollectorBinLabel->setGeometry(QRect(440, 325, 20, 20));
        label_38 = new SlGfwLabel(StatusFormUi);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(470, 345, 71, 31));
        label_50 = new SlGfwLabel(StatusFormUi);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(113, 271, 32, 20));
        label_24 = new SlGfwLabel(StatusFormUi);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(-1, 271, 91, 20));
        label_24->setHmiFontSize(-4);
        label_24->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        L_SMWSpeedLineEdit = new SlGfwLineEdit(StatusFormUi);
        L_SMWSpeedLineEdit->setObjectName(QString::fromUtf8("L_SMWSpeedLineEdit"));
        L_SMWSpeedLineEdit->setGeometry(QRect(63, 271, 48, 20));
        L_SMWSpeedLineEdit->setAlignment(Qt::AlignLeading);
        L_SMWSpeedLineEdit->setReadOnly(true);
        label_52 = new SlGfwLabel(StatusFormUi);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(480, 271, 80, 20));
        label_52->setHmiFontSize(-4);
        label_52->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        R_SMWSpeedLineEdit = new SlGfwLineEdit(StatusFormUi);
        R_SMWSpeedLineEdit->setObjectName(QString::fromUtf8("R_SMWSpeedLineEdit"));
        R_SMWSpeedLineEdit->setGeometry(QRect(450, 271, 48, 20));
        R_SMWSpeedLineEdit->setAlignment(Qt::AlignLeading);
        R_SMWSpeedLineEdit->setReadOnly(true);
        label_53 = new SlGfwLabel(StatusFormUi);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(411, 271, 32, 20));
        ControlModeLabel = new SlGfwLabel(StatusFormUi);
        ControlModeLabel->setObjectName(QString::fromUtf8("ControlModeLabel"));
        ControlModeLabel->setGeometry(QRect(0, 22, 98, 30));
        QWidget::setTabOrder(L_TemparatureLineEdit, R_TemparatureLineEdit);
        QWidget::setTabOrder(R_TemparatureLineEdit, LH_CutBiasLineEdit);
        QWidget::setTabOrder(LH_CutBiasLineEdit, LV_CutBiasLineEdit);
        QWidget::setTabOrder(LV_CutBiasLineEdit, RH_CutBiasLineEdit);
        QWidget::setTabOrder(RH_CutBiasLineEdit, RV_CutBiasLineEdit);
        QWidget::setTabOrder(RV_CutBiasLineEdit, L_MillingLengthLineEdit);
        QWidget::setTabOrder(L_MillingLengthLineEdit, R_MillingLengthLineEdit);
        QWidget::setTabOrder(R_MillingLengthLineEdit, LH_SensorValueLineEdit1);
        QWidget::setTabOrder(LH_SensorValueLineEdit1, LV_SensorValueLineEdit1);
        QWidget::setTabOrder(LV_SensorValueLineEdit1, RH_SensorValueLineEdit1);
        QWidget::setTabOrder(RH_SensorValueLineEdit1, RV_SensorValueLineEdit1);
        QWidget::setTabOrder(RV_SensorValueLineEdit1, LH_SensorValueLineEdit2);
        QWidget::setTabOrder(LH_SensorValueLineEdit2, LV_SensorValueLineEdit2);
        QWidget::setTabOrder(LV_SensorValueLineEdit2, RH_SensorValueLineEdit2);
        QWidget::setTabOrder(RH_SensorValueLineEdit2, RV_SensorValueLineEdit2);
        QWidget::setTabOrder(RV_SensorValueLineEdit2, LH_MotorCurPosLineEdit);
        QWidget::setTabOrder(LH_MotorCurPosLineEdit, LV_MotorCurPosLineEdit);
        QWidget::setTabOrder(LV_MotorCurPosLineEdit, RH_MotorCurPosLineEdit);
        QWidget::setTabOrder(RH_MotorCurPosLineEdit, RV_MotorCurPosLineEdit);
        QWidget::setTabOrder(RV_MotorCurPosLineEdit, LH_MotorDistToGoLineEdit);
        QWidget::setTabOrder(LH_MotorDistToGoLineEdit, LV_MotorDistToGoLineEdit);
        QWidget::setTabOrder(LV_MotorDistToGoLineEdit, RH_MotorDistToGoLineEdit);
        QWidget::setTabOrder(RH_MotorDistToGoLineEdit, RV_MotorDistToGoLineEdit);
        QWidget::setTabOrder(RV_MotorDistToGoLineEdit, L_AxisAngularSpeedLineEdit);
        QWidget::setTabOrder(L_AxisAngularSpeedLineEdit, R_AxisAngularSpeedLineEdit);

        retranslateUi(StatusFormUi);

        QMetaObject::connectSlotsByName(StatusFormUi);
    } // setupUi

    void retranslateUi(SlGfwDialogForm *StatusFormUi)
    {
        label->setStyleSheet(QApplication::translate("StatusFormUi", "background-color: rgb(255, 255, 0)", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("StatusFormUi", "\344\275\234\344\270\232\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("StatusFormUi", "\345\267\246\351\233\206\345\261\221\344\273\223", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("StatusFormUi", "\346\234\272\350\275\246\351\200\232\344\277\241", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QString());
        label_2->setStyleSheet(QApplication::translate("StatusFormUi", "background-color: rgb(0, 0, 0);", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("StatusFormUi", "\345\267\246\351\223\243\345\211\212\345\215\225\345\205\203", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("StatusFormUi", "\346\250\252\345\220\221\344\274\240\346\204\237\345\231\250", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("StatusFormUi", "\342\204\203", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("StatusFormUi", "\345\236\202\345\220\221\344\274\240\346\204\237\345\231\250", 0, QApplication::UnicodeUTF8));
        label_3->setStyleSheet(QApplication::translate("StatusFormUi", "background-color: rgb(0, 0, 0);", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("StatusFormUi", "\345\217\263\351\223\243\345\211\212\345\215\225\345\205\203", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("StatusFormUi", "\345\236\202\345\220\221\344\274\240\346\204\237\345\231\250", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("StatusFormUi", "\346\250\252\345\220\221\344\274\240\346\204\237\345\231\250", 0, QApplication::UnicodeUTF8));
        LV_SensorLabel1->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        LV_SensorLabel1->setText(QString());
        LH_SensorLabel1->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        LH_SensorLabel1->setText(QString());
        LH_SensorLabel2->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        LH_SensorLabel2->setText(QString());
        LV_SensorLabel2->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        LV_SensorLabel2->setText(QString());
        RH_SensorLabel2->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        RH_SensorLabel2->setText(QString());
        RV_SensorLabel2->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        RV_SensorLabel2->setText(QString());
        RV_SensorLabel1->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        RV_SensorLabel1->setText(QString());
        RH_SensorLabel1->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        RH_SensorLabel1->setText(QString());
        label_19->setText(QApplication::translate("StatusFormUi", "\345\212\240\345\267\245\351\225\277\345\272\246", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("StatusFormUi", "\345\212\240\345\267\245\351\225\277\345\272\246", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("StatusFormUi", "m", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("StatusFormUi", "m", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("StatusFormUi", "\345\236\202\345\220\221", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("StatusFormUi", "\347\224\265\346\234\272\345\200\274", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("StatusFormUi", "\344\274\240\346\204\237\345\231\2501", 0, QApplication::UnicodeUTF8));
        LH_SensorValueLineEdit1->setStyleSheet(QApplication::translate("StatusFormUi", "border-color: rgb(255, 0, 0);", 0, QApplication::UnicodeUTF8));
        LH_SensorValueLineEdit1->setValue(QString());
        label_25->setText(QApplication::translate("StatusFormUi", "\347\224\265\346\234\272\344\275\231\347\250\213", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("StatusFormUi", "\346\250\252\345\220\221", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("StatusFormUi", "\345\236\202\345\220\221", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("StatusFormUi", "\346\250\252\345\220\221", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("StatusFormUi", "\345\210\200\347\233\230\350\275\254\351\200\237", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("StatusFormUi", "r/min", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("StatusFormUi", "r/min", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("StatusFormUi", "\344\274\240\346\204\237\345\231\2502", 0, QApplication::UnicodeUTF8));
        label_55->setText(QApplication::translate("StatusFormUi", "\350\275\257\344\273\266\351\235\264", 0, QApplication::UnicodeUTF8));
        label_56->setText(QApplication::translate("StatusFormUi", "\347\233\256\346\240\207\345\200\274", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("StatusFormUi", "LY", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("StatusFormUi", "LZ", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("StatusFormUi", "RY", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("StatusFormUi", "RZ", 0, QApplication::UnicodeUTF8));
        L_PressShoeLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        L_PressShoeLabel->setText(QString());
        label_11->setText(QApplication::translate("StatusFormUi", "\345\216\213\351\235\264\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        R_PressShoeLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        R_PressShoeLabel->setText(QString());
        label_12->setText(QApplication::translate("StatusFormUi", "\345\216\213\351\235\264\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("StatusFormUi", "bar", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("StatusFormUi", "\346\266\262\345\216\213\345\217\230\351\200\201\345\231\250", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("StatusFormUi", "\346\266\262\345\216\213\345\217\230\351\200\201\345\231\250", 0, QApplication::UnicodeUTF8));
        label_51->setText(QApplication::translate("StatusFormUi", "bar", 0, QApplication::UnicodeUTF8));
        label_54->setText(QApplication::translate("StatusFormUi", "\345\267\245\344\275\234\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        label_57->setText(QApplication::translate("StatusFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_58->setText(QApplication::translate("StatusFormUi", "\346\265\213\351\200\237\350\275\256P", 0, QApplication::UnicodeUTF8));
        label_59->setText(QApplication::translate("StatusFormUi", "\346\265\213\351\200\237\350\275\256P", 0, QApplication::UnicodeUTF8));
        label_60->setText(QApplication::translate("StatusFormUi", "mm", 0, QApplication::UnicodeUTF8));
        label_61->setText(QApplication::translate("StatusFormUi", "\346\211\223\347\243\250\347\212\266\346\200\201", 0, QApplication::UnicodeUTF8));
        L_CollectorBinLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        L_CollectorBinLabel->setText(QString());
        TrainCommLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        TrainCommLabel->setText(QString());
        label_30->setText(QApplication::translate("StatusFormUi", "\351\200\232\351\201\2231 NC", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("StatusFormUi", "\346\211\223\347\243\250\350\243\205\347\275\256", 0, QApplication::UnicodeUTF8));
        CH1NCLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        CH1NCLabel->setText(QString());
        GrindLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        GrindLabel->setText(QString());
        label_32->setText(QApplication::translate("StatusFormUi", "\351\200\232\351\201\2232 NC", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("StatusFormUi", "\350\243\205\347\275\256\351\224\201\345\256\232", 0, QApplication::UnicodeUTF8));
        CH2NCLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        CH2NCLabel->setText(QString());
        LockLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        LockLabel->setText(QString());
        BogyLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        BogyLabel->setText(QString());
        label_39->setText(QApplication::translate("StatusFormUi", "\345\217\263\351\233\206\345\261\221\344\273\223", 0, QApplication::UnicodeUTF8));
        R_CollectorBinLabel->setStyleSheet(QApplication::translate("StatusFormUi", "border-image:url(C:/scr/redball.png)", 0, QApplication::UnicodeUTF8));
        R_CollectorBinLabel->setText(QString());
        label_38->setText(QApplication::translate("StatusFormUi", "\345\210\232\346\200\247\346\224\257\346\222\221", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("StatusFormUi", "km/h", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("StatusFormUi", "\346\265\213\351\200\237\350\275\256V", 0, QApplication::UnicodeUTF8));
        label_52->setText(QApplication::translate("StatusFormUi", "\346\265\213\351\200\237\350\275\256V", 0, QApplication::UnicodeUTF8));
        label_53->setText(QApplication::translate("StatusFormUi", "km/h", 0, QApplication::UnicodeUTF8));
        ControlModeLabel->setStyleSheet(QApplication::translate("StatusFormUi", "background-color: rgb(0, 255, 255)", 0, QApplication::UnicodeUTF8));
        ControlModeLabel->setText(QString());
        Q_UNUSED(StatusFormUi);
    } // retranslateUi

};

namespace Ui {
    class StatusFormUi: public Ui_StatusFormUi {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_STATUSFORM_H
